# Generated by Django 4.1.7 on 2023-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenger',
            name='img',
            field=models.ImageField(default='jkj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
